WebApp_TestApp_W3_InlvrOpdr/Controllers/BerichtsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp_TestApp_W3_InlvrOpdr.Models;

namespace WebApp_TestApp_W3_InlvrOpdr.Controllers
{
    public class BerichtsController : Controller
    {
        private readonly AppDBContext _context;

        public BerichtsController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Berichts
        public async Task<IActionResult> Index()
        {
              return _context.Bericht != null ? 
                          View(await _context.Bericht.ToListAsync()) :
                          Problem("Entity set 'AppDBContext.Bericht'  is null.");
        }

        // GET: Berichts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Bericht == null)
            {
                return NotFound();
            }

            var bericht = await _context.Bericht
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bericht == null)
            {
                return NotFound();
            }

            return View(bericht);
        }

        // GET: Berichts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Berichts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Inhoud,Datum")] Bericht bericht)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bericht);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bericht);
        }

        // GET: Berichts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Bericht == null)
            {
                return NotFound();
            }

            var bericht = await _context.Bericht.FindAsync(id);
            if (bericht == null)
            {
                return NotFound();
            }
            return View(bericht);
        }

        // POST: Berichts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Inhoud,Datum")] Bericht bericht)
        {
            if (id != bericht.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bericht);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BerichtExists(bericht.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bericht);
        }

        // GET: Berichts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Bericht == null)
            {
                return NotFound();
            }

            var bericht = await _context.Bericht
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bericht == null)
            {
                return NotFound();
            }

            return View(bericht);
        }

        // POST: Berichts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Bericht == null)
            {
                return Problem("Entity set 'AppDBContext.Bericht'  is null.");
            }
            var bericht = await _context.Bericht.FindAsync(id);
            if (bericht != null)
            {
                _context.Bericht.Remove(bericht);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BerichtExists(int id)
        {
          return (_context.Bericht?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApp_TestApp_W3_InlvrOpdr/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp_TestApp_W3_InlvrOpdr.Models;

namespace WebApp_TestApp_W3_InlvrOpdr.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly AppDBContext _context;

        public CategoriesController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            var appDBContext = _context.Categorieën.Include(c => c.Postzegel);
            return View(await appDBContext.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categorieën == null)
            {
                return NotFound();
            }

            var categorie = await _context.Categorieën
                .Include(c => c.Postzegel)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categorie == null)
            {
                return NotFound();
            }

            return View(categorie);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            ViewData["PostzegelId"] = new SelectList(_context.Postzegels, "Id", "Id");
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CategorieNaam,Beschrijving,PostzegelId")] Categorie categorie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(categorie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PostzegelId"] = new SelectList(_context.Postzegels, "Id", "Id", categorie.PostzegelId);
            return View(categorie);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categorieën == null)
            {
                return NotFound();
            }

            var categorie = await _context.Categorieën.FindAsync(id);
            if (categorie == null)
            {
                return NotFound();
            }
            ViewData["PostzegelId"] = new SelectList(_context.Postzegels, "Id", "Id", categorie.PostzegelId);
            return View(categorie);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CategorieNaam,Beschrijving,PostzegelId")] Categorie categorie)
        {
            if (id != categorie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categorie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategorieExists(categorie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PostzegelId"] = new SelectList(_context.Postzegels, "Id", "Id", categorie.PostzegelId);
            return View(categorie);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categorieën == null)
            {
                return NotFound();
            }

            var categorie = await _context.Categorieën
                .Include(c => c.Postzegel)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categorie == null)
            {
                return NotFound();
            }

            return View(categorie);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categorieën == null)
            {
                return Problem("Entity set 'AppDBContext.Categorieën'  is null.");
            }
            var categorie = await _context.Categorieën.FindAsync(id);
            if (categorie != null)
            {
                _context.Categorieën.Remove(categorie);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategorieExists(int id)
        {
          return (_context.Categorieën?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApp_TestApp_W3_InlvrOpdr/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp_TestApp_W3_InlvrOpdr.Models;

namespace WebApp_TestApp_W3_InlvrOpdr.Controllers
{
    public class ForumController : Controller
    {
        private readonly AppDBContext _context;

        public ForumController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Forum
        public async Task<IActionResult> Index()
        {
              return _context.Forum != null ? 
                          View(await _context.Forum.ToListAsync()) :
                          Problem("Entity set 'AppDBContext.Forum'  is null.");
        }

        // GET: Forum/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Forum == null)
            {
                return NotFound();
            }

            var forum = await _context.Forum
                .FirstOrDefaultAsync(m => m.Id == id);
            if (forum == null)
            {
                return NotFound();
            }

            return View(forum);
        }

        // GET: Forum/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Forum/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naam,Beschrijving")] Forum forum)
        {
            if (ModelState.IsValid)
            {
                _context.Add(forum);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(forum);
        }

        // GET: Forum/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Forum == null)
            {
                return NotFound();
            }

            var forum = await _context.Forum.FindAsync(id);
            if (forum == null)
            {
                return NotFound();
            }
            return View(forum);
        }

        // POST: Forum/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naam,Beschrijving")] Forum forum)
        {
            if (id != forum.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(forum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ForumExists(forum.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(forum);
        }

        // GET: Forum/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Forum == null)
            {
                return NotFound();
            }

            var forum = await _context.Forum
                .FirstOrDefaultAsync(m => m.Id == id);
            if (forum == null)
            {
                return NotFound();
            }

            return View(forum);
        }

        // POST: Forum/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Forum == null)
            {
                return Problem("Entity set 'AppDBContext.Forum'  is null.");
            }
            var forum = await _context.Forum.FindAsync(id);
            if (forum != null)
            {
                _context.Forum.Remove(forum);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ForumExists(int id)
        {
          return (_context.Forum?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApp_TestApp_W3_InlvrOpdr/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp_TestApp_W3_InlvrOpdr</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp_TestApp_W3_InlvrOpdr.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/materia.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <b><a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp_TestApp_W3_InlvrOpdr</a></b>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <b>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item1">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item2">
                            <a class="nav-link text-white" asp-area="" asp-controller="Postzegels" asp-action="Index">Postzegels</a>
                        </li>
                        <li class="nav-item3">
                            <a class="nav-link text-white" asp-area="" asp-controller="Categories" asp-action="Index">Categorieën</a>
                        </li>
                        <li class="nav-item4">
                            <a class="nav-link text-white" asp-area="" asp-controller="Gebruikers" asp-action="Index">Gebruikers</a>
                        </li>
                        <li class="nav-item8">
                            <a class="nav-link text-white" asp-area="" asp-controller="Forum" asp-action="Index">Forum</a>
                        </li>
                        <li class="nav-item9">
                            <a class="nav-link text-white" asp-area="" asp-controller="Berichts" asp-action="Index">Bericht(en)</a>
                        </li>
                        <li class="nav-item5">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy Policy</a>
                        </li>
                        <li class="nav-item6">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Functie">Functies</a>
                        </li>
                        <li class="nav-item7">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Joke">Jokes API</a>
                        </li>
                    </ul>
                </div>
            </div>
            </b>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <style>
       .border-top {
            background-image: linear-gradient(to right, red,orange,yellow,green,blue,indigo,violet);
       }

       .container {
           color:white;
       }

       .navbar{
            background-image: linear-gradient(to right, red,orange,yellow,green,blue,indigo,violet);
       }

        .navbar-nav {
           color: white;
       }

        .navbar-light .navbar-brand{
            color: white;
        }
    </style>

    <center>
    <footer class="border-top footer text-muted">
        <div class="container">
            <b>&copy; 2023 - Nan Ferdinandus - WebApp_TestApp_W3_InlvrOpdr</b>
        </div>
    </footer>
    </center>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>