WebApp_TestApp_W3_InlvrOpdr/Models/Joke.cs
using System.Collections.Generic;

namespace WebApp_TestApp_W3_InlvrOpdr.Models
{
    public class Joke
    {
        public List<string>? categories { get; set; }
        public string? created_at { get; set; }
        public string? icon_url { get; set; }
        public string? id { get; set; }
        public string? updated_at { get; set; }
        public string? url { get; set; }
        public string? value { get; set; }
    }
}

WebApp_TestApp_W3_InlvrOpdr/Models/Postzegel.cs
namespace WebApp_TestApp_W3_InlvrOpdr.Models
{
    public class Postzegel
    {
        public int Id { get; set; }
        public string LandVanHerkomst { get; set; }
        public string Conditie { get; set; }
        public int Uitgiftejaar { get; set; }
        public decimal Waarde { get; set; }

        // Navigatie-eigenschap voor de eigenaar van de postzegel
        public Gebruiker Eigenaar { get; set; }
        public bool IsFavoriet { get; set; }
        public int EigenaarId { get; set; }
       //public ICollection<Categorie> Categorieën { get; set; }

    }
}

WebApp_TestApp_W3_InlvrOpdr/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Net.Http;
using System.Threading.Tasks;
using WebApp_TestApp_W3_InlvrOpdr.Models;

namespace WebApp_TestApp_W3_InlvrOpdr.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Joke()
        {
            var joke = await GetRandomJokeAsync();
            return View(joke);
        }

        private async Task<Joke> GetRandomJokeAsync()
        {
            using var client = new HttpClient();
            var response = await client.GetStringAsync("https://api.chucknorris.io/jokes/random");
            return Newtonsoft.Json.JsonConvert.DeserializeObject<Joke>(response);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Functie(string parameter)
        {
            ViewData["Parameter"] = parameter;
            return View();
        }

        public IActionResult Optellen(int num1, int num2)
        {
            int result = num1 + num2;
            ViewData["Result"] = result;
            return View("Functie");
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp_TestApp_W3_InlvrOpdr/Controllers/PostzegelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp_TestApp_W3_InlvrOpdr.Models;

namespace WebApp_TestApp_W3_InlvrOpdr.Controllers
{
    public class PostzegelsController : Controller
    {
        private readonly AppDBContext _context;

        public PostzegelsController(AppDBContext context)
        {
            _context = context;
        }

        // GET: Postzegels
        public IActionResult Index([FromQuery] bool? favoriet = null)
        {
            // Zoek de Gebruiker-entiteit op basis van de gebruikersnaam
            var gebruiker = _context.Gebruikers.FirstOrDefault(u => u.Gebruikersnaam == User.Identity.Name);

            if (gebruiker == null)
            {
                // Gebruiker niet gevonden, return lege lijst
                return View(new List<Postzegel>());
            }

            // Haal de postzegels op voor de huidige gebruiker
            var postzegels = _context.Postzegels
                .Where(p =>
                    p.EigenaarId == gebruiker.Id &&
                    (favoriet == null || p.IsFavoriet == favoriet)
                 ).ToList();

            return View(postzegels);
        }


        // GET: Postzegels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Postzegels == null)
            {
                return NotFound();
            }

            var postzegel = await _context.Postzegels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (postzegel == null)
            {
                return NotFound();
            }

            return View(postzegel);
        }

        // GET: Postzegels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Postzegels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,LandVanHerkomst,Conditie,Uitgiftejaar,Waarde,IsFavoriet")] Postzegel postzegel)
        {
            var eigenaar = _context.Gebruikers.FirstOrDefault(u => u.Gebruikersnaam == User.Identity.Name);
            postzegel.Eigenaar = eigenaar;

            ModelState.Clear();
            TryValidateModel(postzegel);

            if (ModelState.IsValid)
            {
                _context.Add(postzegel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(postzegel);
        }



        // GET: Postzegels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Postzegels == null)
            {
                return NotFound();
            }

            var postzegel = await _context.Postzegels.FindAsync(id);
            if (postzegel == null)
            {
                return NotFound();
            }
            return View(postzegel);
        }

        // POST: Postzegels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // POST: Postzegels/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,LandVanHerkomst,Conditie,Uitgiftejaar,Waarde,IsFavoriet")] Postzegel postzegel)
        {
            if (id != postzegel.Id)
            {
                return NotFound();
            }

            var eigenaar = _context.Gebruikers.FirstOrDefault(u => u.Gebruikersnaam == User.Identity.Name);
            postzegel.Eigenaar = eigenaar;

            ModelState.Clear();
            TryValidateModel(postzegel);

            if (ModelState.IsValid)
            {
                try
                {
                    // Haal de bestaande postzegel op uit de database
                    var existingPostzegel = await _context.Postzegels.FindAsync(id);
                    if (existingPostzegel == null)
                    {
                        return NotFound();
                    }

                    // Update de waardes
                    existingPostzegel.LandVanHerkomst = postzegel.LandVanHerkomst;
                    existingPostzegel.Conditie = postzegel.Conditie;
                    existingPostzegel.Uitgiftejaar = postzegel.Uitgiftejaar;
                    existingPostzegel.Waarde = postzegel.Waarde;
                    existingPostzegel.IsFavoriet = postzegel.IsFavoriet;

                    _context.Update(existingPostzegel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostzegelExists(postzegel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(postzegel);
        }



        // GET: Postzegels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Postzegels == null)
            {
                return NotFound();
            }

            var postzegel = await _context.Postzegels
                .FirstOrDefaultAsync(m => m.Id == id);
            if (postzegel == null)
            {
                return NotFound();
            }

            return View(postzegel);
        }

        // POST: Postzegels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Postzegels == null)
            {
                return Problem("Entity set 'AppDBContext.Postzegels'  is null.");
            }
            var postzegel = await _context.Postzegels.FindAsync(id);
            if (postzegel != null)
            {
                _context.Postzegels.Remove(postzegel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostzegelExists(int id)
        {
            return (_context.Postzegels?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApp_TestApp_W3_InlvrOpdr/Views/Home/Functie.cshtml
@{
    var parameterValue = ViewData["Parameter"] as string;
}

<!DOCTYPE html>
<html>
<head>
    <title>Functies</title>
</head>
<body>
    <center>
        <h1>Een pagina met functies</h1>
        <h4>1. Parameter-checker</h4>
        <p><i>De waarde van de parameter is: @parameterValue</i></p>

        <h4>2. Getallen optellen</h4>
        <form method="post" action="@Url.Action("Optellen")">
            <div>
                <label for="num1">Getal 1:</label>
                <input type="number" id="num1" name="num1" />
            </div>
            <div>
                <label for="num2">Getal 2:</label>
                <input type="number" id="num2" name="num2" />
            </div>
            <div>
                <input type="submit" value="Optellen" />
            </div>
        </form>

        @if (ViewData["Result"] != null)
        {
            <p class="resultaat">Resultaat van de optelling: @ViewData["Result"]</p>
        }
    </center>
</body>
</html>

<style>
    p {
        color: black;
    }

    h1 {
        color: red;
    }

    h4 {
        color: black;
    }

    label {
        color: black;
    }

    input[type="submit"] {
        margin-top: 45px;
    }

    p.resultaat {
        margin-top: -65px;
    }
</style>

WebApp_TestApp_W3_InlvrOpdr/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Keuzeopdracht: Verzamelwoede";
}

<div class="text-center">
    <h1 class="display-4"><b>Welkom op deze verzamelpagina, in het thema 'Postzegels'.</b></h1>
    <p><i>Leer meer over deze keuzeopdracht, <a href="https://moodle.zuyd.nl/pluginfile.php/1499643/mod_resource/content/14/Opdracht%20PI4%202023%20gelegenheid%201.pdf">klik hier</a>.</i></p>
</div>

<style>
    .display-4 {
        color: red;
    }

    p {
        color: black;
    }
</style>

WebApp_TestApp_W3_InlvrOpdr/Views/Home/Joke.cshtml
@model WebApp_TestApp_W3_InlvrOpdr.Models.Joke

<!DOCTYPE html>
<html>
<head>
    <title>Joke Page</title>
</head>
<body>
    <center>
    <h1>Chuck Norris Joke API</h1>
    <div>
        <p>@Model.value</p>
        <p><i>Refresh de pagina voor een nieuwe joke!</i></p>
    </div>
    </center>
</body>
</html>


<style>
    p {
        color: black;
    }

    h1 {
        color: red;
    }
</style>

WebApp_TestApp_W3_InlvrOpdr/Views/Home/Postzegels.cshtml
@model List<Postzegel>

<h1>Mijn Postzegels</h1>

<form asp-controller="Postzegels" asp-action="FilterFavorieten" method="post">
    <button type="submit">Filter op Favorieten</button>
</form>

<table>
    <thead>
        <tr>
            <th>Naam</th>
            <th>Is Favoriet</th>
            <!-- Andere kolommen -->
        </tr>
    </thead>
    <tbody>
        @foreach (var postzegel in Model)
        {
            <tr>
                <td>@postzegel.Id</td>
                <td>@(postzegel.IsFavoriet ? "Ja" : "Nee")</td>
                <!-- Andere kolommen -->
            </tr>
        }
    </tbody>
</table>